spring:
#  profiles:
#    active: dev
  application:
    name: joribhaejo-spring
  jpa:
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: Asia/Seoul
    deserialization:
      fail-on-unknown-properties: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  refresh-token-expiration-time: ${JWT_REFRESH_EXP}
  access-token-expiration-time: ${JWT_ACCESS_EXP}

springdoc:
  api-docs:
    path: /api/api-spec
    enabled: true
  swagger-ui:
    path: /api/my-docs
    enabled: true
  override-with-generic-response: false
  use-fqn: true